/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as OccupancyRouteImport } from './routes/occupancy'
import { Route as QuarantineRouteImport } from './routes/quarantine'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TigersIndexRouteImport } from './routes/tigers.index'
import { Route as TigersTigerIdRouteImport } from './routes/tigers.$tigerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const OccupancyRoute = OccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarantineRoute = QuarantineRouteImport.update({
  id: '/quarantine',
  path: '/quarantine',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TigersIndexRoute = TigersIndexRouteImport.update({
  id: '/tigers/',
  path: '/tigers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TigersTigerIdRoute = TigersTigerIdRouteImport.update({
  id: '/tigers/$tigerId',
  path: '/tigers/$tigerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/ingest': typeof IngestRoute
  '/occupancy': typeof OccupancyRoute
  '/quarantine': typeof QuarantineRoute
  '/settings': typeof SettingsRoute
  '/tigers/$tigerId': typeof TigersTigerIdRoute
  '/tigers/': typeof TigersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/ingest': typeof IngestRoute
  '/occupancy': typeof OccupancyRoute
  '/quarantine': typeof QuarantineRoute
  '/settings': typeof SettingsRoute
  '/tigers/$tigerId': typeof TigersTigerIdRoute
  '/tigers': typeof TigersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/ingest': typeof IngestRoute
  '/occupancy': typeof OccupancyRoute
  '/quarantine': typeof QuarantineRoute
  '/settings': typeof SettingsRoute
  '/tigers/$tigerId': typeof TigersTigerIdRoute
  '/tigers/': typeof TigersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/ingest'
    | '/occupancy'
    | '/quarantine'
    | '/settings'
    | '/tigers/$tigerId'
    | '/tigers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/ingest'
    | '/occupancy'
    | '/quarantine'
    | '/settings'
    | '/tigers/$tigerId'
    | '/tigers'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/ingest'
    | '/occupancy'
    | '/quarantine'
    | '/settings'
    | '/tigers/$tigerId'
    | '/tigers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  IngestRoute: typeof IngestRoute
  OccupancyRoute: typeof OccupancyRoute
  QuarantineRoute: typeof QuarantineRoute
  SettingsRoute: typeof SettingsRoute
  TigersTigerIdRoute: typeof TigersTigerIdRoute
  TigersIndexRoute: typeof TigersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occupancy': {
      id: '/occupancy'
      path: '/occupancy'
      fullPath: '/occupancy'
      preLoaderRoute: typeof OccupancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarantine': {
      id: '/quarantine'
      path: '/quarantine'
      fullPath: '/quarantine'
      preLoaderRoute: typeof QuarantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tigers/': {
      id: '/tigers/'
      path: '/tigers'
      fullPath: '/tigers/'
      preLoaderRoute: typeof TigersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tigers/$tigerId': {
      id: '/tigers/$tigerId'
      path: '/tigers/$tigerId'
      fullPath: '/tigers/$tigerId'
      preLoaderRoute: typeof TigersTigerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  IngestRoute: IngestRoute,
  OccupancyRoute: OccupancyRoute,
  QuarantineRoute: QuarantineRoute,
  SettingsRoute: SettingsRoute,
  TigersTigerIdRoute: TigersTigerIdRoute,
  TigersIndexRoute: TigersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
